export const projectsData = [
    {
        id: 7,
        domain: "web",
        head: "Business Website",
        isHosted: true,
        link: "https://agency-website-zeta.vercel.app/",
        gitlink: "https://github.com/Sriramprasath04/Agency-Website",
        stack: [{l:"React.js"}, {l:"Tailwind CSS"}],
        cont: "I have build a Business website template using React.js and Tailwind CSS",
    },
    {
        id : 6,
        domain: "web",
        head : "Portfolio v-2",
        isHosted : true,
        link: "https://portfolio-v2-seven-kappa.vercel.app/",
        gitlink: "https://github.com/Sriramprasath04/Portfolio-v2",
        stack : [{l:"React.js"}, {l:"React-Router"}, {l:"Tailwind CSS"}],
        cont : "Updated version of my portfolio website with modern web technologies.",
    },
    {
        id : 5,
        domain: "web",
        head : "Chef Food",
        isHosted : false,
        link: "",
        gitlink: "https://github.com/Sriramprasath04/FoodOrderingApp",
        stack : [{l:"React.js"}, {l:"React-Router"}, {l:"CSS3"}],
        cont : "Food Ordering application that enhances the food ordering experience.",
    },
    {
        id : 4,
        domain: "java",
        head : "Railway Reservation System",
        isHosted : false,
        link: "",
        gitlink: "https://github.com/Sriramprasath04/Railway-Reservation-System",
        stack : [{l:"Java ( OOPs )"}],
        cont : "This application immitates functionalities of the Railway Reservation System.",
    },
    {
        id : 3,
        domain: "java",
        head : "Hangman Game",
        isHosted : false,
        link: "",
        gitlink: "https://github.com/Sriramprasath04/Hangman-Game",
        stack : [{l:"Java"}],
        cont : "It's a word gussing game. It help childerns learn new words, improve your spelling, and practice your vocabulary.",
    },
    {
        id : 2,
        domain: "web",
        head : "Amazon Clone",
        isHosted : true,
        link: "https://sriramprasath04.github.io/Amazon-clone/",
        gitlink: "https://github.com/Sriramprasath04/Amazon-clone",
        stack : [{l:"HTML5"},{l:"CSS3"}],
        cont : "It's a simple demonstration of how to recreate the look and feel of one of the world's most popular e-commerce websites.",
    },
    {
        id : 1,
        domain: "web",
        head : "Portfolio v-1",
        isHosted : true,
        link: "https://sriramprasath04.github.io/Personal-Portfolio/",
        gitlink: "https://github.com/Sriramprasath04/Personal-Portfolio",
        stack : [{l:"HTML5"}, {l:"CSS3"}, {l:"JavaScript"}],
        cont : "My first portfolio website that I've designed and build.",
    },
];
